version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  access:
    format: '%(asctime)s - %(client_addr)s - "%(request_line)s" %(status_code)s'

handlers:
  default:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

loggers:
  uvicorn.access:
    level: CRITICAL
    handlers: []
    propagate: false
  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: false

root:
  level: INFO
  handlers: [default]
